# This script takes a the TSV of headers and species produced by 6.1_summarize_diff_causes.py and does a deeper dive
# to identify if the differences are due to rounding. It runs each species through v1 and v2 again, but with
# window means saved. v1 is run only on the unexplained headers, using a wij file generated by v2 to save time.
# It then compares the window means between versions and checks if differences in rounding at the minimum positions
# or ramp edge positions can explain the differences in ramp results.
# Headers still not explained are plotted for visual inspection.
# All intermediate files are saved in the ../outputs/unexplained/ folder.
# An updated benchmark1_difference_explanation-{MEAN}.tsv file is produced based on the results, updating the unexplained column.

import sys
import os
import numpy as np
import matplotlib.pyplot as plt

def get_unexplained_differences(unexplained_tsv):
    species_id_dict = {}
    with open(unexplained_tsv) as inf:
        for line in inf:
            line = line.strip()
            items = line.split("\t")
            species_id = items[0]
            taxon_group = items[1]
            header = items[2]
            if species_id not in species_id_dict:
                species_id_dict[species_id] = {
                    "taxon_group": taxon_group,
                    "headers": []
                }
            species_id_dict[species_id]["headers"].append(header)
    return species_id_dict

def create_truncated_input_fasta(input_fasta, output_fasta, headers):
    headers_seen = set()
    with open(input_fasta) as inf, open(output_fasta, "w") as outf:
        for line in inf:
            if len(headers_seen) == len(headers):
                break
            if line.startswith(">"):
                header = line.strip()
                seq = inf.readline().strip()
                if header in headers:
                    headers_seen.add(header)
                    outf.write(f"{header}\n{seq}\n")
    if len(headers_seen) != len(headers):
        print(f"\tWarning: Not all headers were found in {input_fasta}. Found {len(headers_seen)} out of {len(headers)}.")

def get_ramp(path, header):
    with open(path) as inf:
        for line in inf:
            line = line.strip()
            if line == header:
                return inf.readline().strip()
    return ""

def get_window_means_v1(path, header):
    window_means = []
    with open(path) as inf:
        for line in inf:
            line = line.strip().replace('"', "")
            if line.startswith(header):
                window_mean = float(line.split(",")[-1])
                window_means.append(window_mean)
    # append a NaN to the end since v1 window means are one value shorter
    window_means.append(np.nan)
    return np.array(window_means)

def get_window_means_v2(path, header):
    with open(path) as inf:
        for line in inf:
            line = line.strip()
            if line == header:
                window_means = inf.readline().split(",")
                window_means = [float(windowMean) for windowMean in window_means]
                return np.array(window_means)
    return None

def plot_window_means(window_means1, window_means2, header, species_id, fig_path):
    plt.figure(figsize=(10, 6))
    x = np.arange(len(window_means1))
    plt.plot(x, window_means2, label="v2.0")
    plt.plot(x, window_means1, label="v1.0")
    plt.ylim(0, 1.25)
    # plot a horizontal line at 8% or gene length
    plt.axvline(x=int(0.08*len(window_means1)), color='b', linestyle='--', label='8% Gene Length')
    plt.xlabel("Window")
    plt.ylabel("Window Mean")
    plt.title(f"Window Means for {header} ({species_id})")
    plt.legend()
    plt.savefig(fig_path)
    print(f"\t\tFigure saved")
    plt.close()

if __name__ == "__main__":
    MEAN = "hmean"
    WINDOW = 9
    BASE_OUTPUT_DIR = "../outputs/unexplained"
    unexplained_tsv = "../outputs/unexplained_differences.tsv"
    old_difference_explaination_tsv = f"../outputs/benchmark1_difference_explanation-{MEAN}.tsv"
    new_difference_explanation_tsv = f"../outputs/benchmark1_difference_explanation-final-{MEAN}.tsv"

    species_id_dict = get_unexplained_differences(unexplained_tsv)

    num_total_headers = sum(len(info["headers"]) for info in species_id_dict.values())
    num_explained_rounding = 0
    num_still_unexplained = 0
    headers_still_unexplained = {}

    for species_id, info in species_id_dict.items():
        taxon_group = info["taxon_group"]
        headers = info["headers"]
        print(f"Species ID: {species_id}, Taxon Group: {taxon_group}: headers: {len(headers)}")

        # Create output directories for v1 and v2 if they don't exist
        TAXON_PATH1 = f"{BASE_OUTPUT_DIR}/1.0/{MEAN}/{taxon_group}"
        TAXON_PATH2 = f"{BASE_OUTPUT_DIR}/2.0/{MEAN}/{taxon_group}"
        if not os.path.exists(TAXON_PATH1):
            os.makedirs(TAXON_PATH1)
        if not os.path.exists(TAXON_PATH2):
            os.makedirs(TAXON_PATH2)

        # Define paths for intermediate files
        input_fasta = f"../inputs/filtered/{taxon_group}/{species_id}/cds_from_genomic.fna"
        # created to contain only the relevant headers and sequences for v1 (to save time)
        input1_fasta = f"{TAXON_PATH1}/{species_id}-cds_from_genomic.fna"
        ramps1_path = f"{TAXON_PATH1}/{species_id}-{MEAN}-w9-ramps.fa"
        ramps2_path = f"{TAXON_PATH2}/{species_id}-{MEAN}-w9-ramps.fa"
        window_means1_path = f"{TAXON_PATH1}/{species_id}-{MEAN}-w9-windowMeans.csv"
        window_means2_path = f"{TAXON_PATH2}/{species_id}-{MEAN}-w9-windowMeans.fa"
        wij_path = f"{TAXON_PATH2}/{species_id}-{MEAN}-w9-wij.csv"

        # Run ExtRamp v2 to get window means if not already done
        if not os.path.exists(window_means2_path) or not os.path.exists(ramps2_path) or not os.path.exists(wij_path):
            cmd = f"python ExtRamp2.0.py -t 4 -m {MEAN} -w 9 -i {input_fasta} -o {ramps2_path} -l {window_means2_path} -j {wij_path}"
            print(f"\tRunning ExtRamp v2 for {species_id}")
            os.system(cmd)

        # If input1_fasta doesn't exist, copy the relevant headers and sequences from input_fasta to input1_fasta
        if not os.path.exists(input1_fasta):
            create_truncated_input_fasta(input_fasta, input1_fasta, headers)
        
        # Run ExtRamp v1 to get window means if not already done
        if not os.path.exists(window_means1_path) or not os.path.exists(ramps1_path):
            cmd = f"python ExtRamp1.0.py -t 4 -m {MEAN} -w 9 -i {input1_fasta} -a {wij_path} -o {ramps1_path} -l {window_means1_path}"
            print(f"\tRunning ExtRamp v1 for {species_id}")
            os.system(cmd)
        
        for header in headers:
            print(f"\tHeader: {header}")
            # Get the ramp for the header for both versions
            ramp1 = get_ramp(ramps1_path, header)
            ramp2 = get_ramp(ramps2_path, header)

            if ramp1 and ramp2:
                if ramp1 != ramp2:
                    print("\t\tRamp is a different length between versions")
                else:
                    print("\t\tERROR: the ramps are the same, but are expected to be different based on a previous step")
            elif ramp1:
                print("\t\tThe ramp is lost in v2")
            elif ramp2:
                print("\t\tThe ramp is gained in v2")

            
            # Get the window means for the header for both versions
            window_means1 = get_window_means_v1(window_means1_path, header)
            window_means2 = get_window_means_v2(window_means2_path, header)

            if len(window_means1) == 0:
                print(f"\t\tERROR: could not find header in window means file 1: {header}")
                exit(1)
            if window_means2 is None or len(window_means2) == 0:
                print(f"\t\tERROR: could not find header in window means file 2: {header}")
                exit(1)
            
            # Check if min mean changed position
            window_means1_min = min(window_means1)
            min1_pos = np.where(window_means1 == window_means1_min)[0][0]
            window_means2_min = min(window_means2)
            min2_pos = np.where(window_means2 == window_means2_min)[0][0]

            # check if the change in min position was the cause for the change in ramp status
            perc1 = float(100*(min1_pos/float(len(window_means1))))
            perc2 = float(100*(min2_pos/float(len(window_means2))))

            v1_min1_pos_val = window_means1[min1_pos]
            v1_min2_pos_val = window_means1[min2_pos]
            v2_min1_pos_val = window_means2[min1_pos]
            v2_min2_pos_val = window_means2[min2_pos]

            if min1_pos != min2_pos and (perc1 <= 8) != (perc2 <= 8) and (v1_min1_pos_val != v2_min1_pos_val or v1_min2_pos_val != v2_min2_pos_val):
                print(f"\t\tMin index changed from {min1_pos} to {min2_pos}")
                print(f"\t\tValues at pos {min1_pos}: v1.0 {v1_min1_pos_val:.16f} v2.0 {v2_min1_pos_val:.16f} diff {v1_min1_pos_val-v2_min1_pos_val:.16f}")
                print(f"\t\tValues at pos {min2_pos}: v1.0 {v1_min2_pos_val:.16f} v2.0 {v2_min2_pos_val:.16f} diff {v1_min2_pos_val-v2_min2_pos_val:.16f}")
                print(f"\t\tv1.0 {perc1}({perc1 <= 8}) v2.0 {perc2}({perc2 <= 8})")
                print("\t\tDiff explained by change in min pos")
                num_explained_rounding += 1
            elif ramp1 and ramp2 and len(ramp1) != len(ramp2):
                # get the indices where the window mean goes above the mean of the sequence
                v1_window_mean_cutoff = int((len(ramp1) / 3) - WINDOW)
                v2_window_mean_cutoff = int((len(ramp2) / 3) - WINDOW)
                v1_cutoff1_val = window_means1[v1_window_mean_cutoff]
                v1_cutoff2_val = window_means1[v2_window_mean_cutoff]
                v2_cutoff1_val = window_means2[v2_window_mean_cutoff]
                v2_cutoff2_val = window_means2[v1_window_mean_cutoff]

                if (v1_cutoff1_val != v2_cutoff1_val) or (v1_cutoff2_val != v2_cutoff2_val):
                    print(f"\t\tRamp length changed from {len(ramp1)} to {len(ramp2)}")
                    print(f"\t\tValues at v1 cutoff pos {v1_window_mean_cutoff}: v1.0 {v1_cutoff1_val:.16f} v2.0 {v2_cutoff1_val:.16f} diff {v1_cutoff1_val-v2_cutoff1_val:.16f}")
                    print(f"\t\tValues at v2 cutoff pos {v2_window_mean_cutoff}: v1.0 {v1_cutoff2_val:.16f} v2.0 {v2_cutoff2_val:.16f} diff {v1_cutoff2_val-v2_cutoff2_val:.16f}")
                    print("\t\tDiff explained by change in rounding at ramp length cutoff")
                    num_explained_rounding += 1
                else:
                    print("\t\tDiff not explained by rounding at ramp length cutoff")
                    num_still_unexplained += 1
                    headers_still_unexplained[header] = species_id
                    # plot the window means to see if there is a visual difference
                    fig_path = f"{BASE_OUTPUT_DIR}/{species_id}-{header.replace(' ', '_')}-window_means.png"
                    plot_window_means(window_means1, window_means2, header, species_id, fig_path)
            elif min1_pos == min2_pos:
                v1_min_pos_val = window_means1[min1_pos]
                v2_min_pos_val = window_means2[min1_pos]
                if v1_min_pos_val != v2_min_pos_val:
                    print(f"\t\tMin index the same at {min1_pos}")
                    print(f"\t\tValues at pos {min1_pos}: v1.0 {v1_min_pos_val:.16f} v2.0 {v2_min_pos_val:.16f} diff {v1_min_pos_val-v2_min_pos_val:.16f}")
                    print("\t\tDiff explained by change in rounding at min position")
                    num_explained_rounding += 1
                else:
                    print("\t\tDiff not explained by change in rounding at shared min pos")
                    num_still_unexplained += 1
                    headers_still_unexplained[header] = species_id
                    # plot the window means to see if there is a visual difference
                    fig_path = f"{BASE_OUTPUT_DIR}/{species_id}-{header.replace(' ', '_')}-window_means.png"
                    plot_window_means(window_means1, window_means2, header, species_id, fig_path)
            else:
                print("\t\tDiff not explained by change in min pos")
                num_still_unexplained += 1
                headers_still_unexplained[header] = species_id
                # plot the window means to see if there is a visual difference
                fig_path = f"{BASE_OUTPUT_DIR}/{species_id}-{header.replace(' ', '_')}-window_means.png"
                plot_window_means(window_means1, window_means2, header, species_id, fig_path)

    # Write updated difference explanation TSV
    with open(old_difference_explaination_tsv) as inf, open(new_difference_explanation_tsv, "w") as outf:
        header = inf.readline()
        outf.write(header)

        # Read in the results
        data = inf.readline().strip().split("\t")
        total_sequences = int(data[0])
        total_diff_1_2 = int(data[1])
        total_diff_1_1_fixed = int(data[2])
        total_diff_1_2_rounding = int(data[3])
        total_diff_1_2_not_explained = int(data[4])
        percent_diff = float(data[5])
        percent_last_window = float(data[6])
        percent_diff_rounding = float(data[7])
        percent_diff_other = float(data[8])

        # Update the results
        total_diff_1_2_not_explained = num_still_unexplained
        total_diff_1_2_rounding += num_explained_rounding
        percent_diff_rounding = (total_diff_1_2_rounding / total_sequences) * 100 if total_sequences > 0 else 0
        percent_diff_other = (total_diff_1_2_not_explained / total_sequences) * 100 if total_sequences > 0 else 0

        # Write the updated results
        outf.write(f"{total_sequences}\t{total_diff_1_2}\t{total_diff_1_1_fixed}\t{total_diff_1_2_rounding}\t{total_diff_1_2_not_explained}\t{percent_diff}\t{percent_last_window}\t{percent_diff_rounding}\t{percent_diff_other}\n")

    print(f"\n\nTotal headers processed: {num_total_headers}")
    print(f"Number of differences explained by change in rounding: {num_explained_rounding}")
    if num_still_unexplained > 0:
        print(f"Number of differences still unexplained: {num_still_unexplained}")
        print(f"For unexplained headers, check the plots:")
        print(f"{headers_still_unexplained}")
    else:
        print("All differences explained by change in rounding")